### PR TITLE
Making HEC idempotent

### PR DESCRIPTION
**Pull request by nwang92**
Addressing https://github.com/splunk/splunk-ansible/issues/373

### CODE REVIEW

**Comment by nwang92** [comment]
Actually, this might not work fully, I'm going to test this.

**Comment by nwang92** [comment]
Ok, this should address the idempotency issues around https://github.com/splunk/splunk-ansible/issues/373 - but it still does not support custom certs.

Changes made:
- Moved HEC variables into nested dict
- Convert Splunk CLI calls for setting up HEC tokens into REST API calls
- Made API calls idempotent; this should support changing anything in `splunk.hec.*` and have the change be reflected upon next container restart

This change may break a few tests in docker-splunk, but I can fix them and add new tests to capture the full change.

**Comment by alishamayor** [comment]
Can you update the docs related to HEC?
The old variable format shows up in the Provision HEC section of [docs/EXAMPLES.md](https://github.com/splunk/splunk-ansible/blob/develop/docs/EXAMPLES.md) and in [docs/advanced/default.yml.spec.md](https://github.com/splunk/splunk-ansible/blob/develop/docs/advanced/default.yml.spec.md).

Also spotted some molecule tests with the old format.

**Comment by nwang92** [comment]
Going to merge this and fix any tests in the subsequent docker-splunk PR here: https://github.com/splunk/docker-splunk/pull/328

**Pull request merged**
