### PR TITLE
Register jre path to Splunk launch

### PR DESCRIPTION
**Pull request by arctan5x**
Also register jre path to Splunk launch in Redhat. Existing 3 tasks can run in both Debian and Redhat. Verified this works with Splunk 8.0.2 and Redhat8 env.

### CODE REVIEW

**Comment by nwang92** [comment]
Actually, you may just want to do this for all platforms? CentOS as well?

**Comment by nwang92** [comment]
Actually, it looks like Java isn't supported on CentOS?

**Comment by alishamayor** [comment]
> Actually, it looks like Java isn't supported on CentOS?

I'm pretty sure you can `yum install java-1.8.0-openjdk-devel`

**Comment by alishamayor** [comment]
(sorry, accidentally hit close and comment)

**Comment by nwang92** [comment]
I wonder if you could also remove the `apt` + `command: microdnf ...` tasks using https://docs.ansible.com/ansible/latest/modules/package_module.html

You probably still need to use conditions on the package name, as it differs from OS-to-OS.

**Pull request merged**
