### PR TITLE
allow manually specifying forward-servers

### PR DESCRIPTION
**Pull request by tod-uma**
In our environment, we have a set of heavy forwarders that are between our indexers and our universal forwarders. This pull request allows us to manually specify our forward servers since there isn't a good way to automatically determine which servers are the ones we want everything to go through.

### CODE REVIEW

**Comment by bb03** [comment]
Hi @tod-uma Can you tell me what kind of tests you ran for these changes?  Especially if you have any test artifacts (like a docker compose template) we would really like to incorporate that into our testing.

**Comment by tod-uma** [comment]
> Hi @tod-uma Can you tell me what kind of tests you ran for these changes? Especially if you have any test artifacts (like a docker compose template) we would really like to incorporate that into our testing.

What I do to test is I run it on our dev systems, which are just vmware vms, then when I'm confident it'll work, I move to our production systems. I'm not familiar with docker compose. Can  you point me to some documentation on how to use it? I'd be happy to run other tests on anything I submit.

**Comment by tod-uma** [comment]
> > Hi @tod-uma Can you tell me what kind of tests you ran for these changes? Especially if you have any test artifacts (like a docker compose template) we would really like to incorporate that into our testing.
> 
> What I do to test is I run it on our dev systems, which are just vmware vms, then when I'm confident it'll work, I move to our production systems. I'm not familiar with docker compose. Can you point me to some documentation on how to use it? I'd be happy to run other tests on anything I submit.

ok, I've got docker working on my desktop box and I'm able to get the make test to mostly work. However, I'm running into an issue where it fails to launch splunk due to an "unsupported filesystem". I suspect that is because my desktop runs on zfs. I'll have to look into that more.

**Comment by bb03** [comment]
@tod-uma Okay thanks, we'll do some testing on our side before we merge it in, so be patient with us while we go through our verification.

**Comment by tod-uma** [comment]
So I've been learning molecule to perform tests. I needed to add support for passing a proxy server to the docker containers. I also added tests specific to the manually specifying forward servers. I'm glad I did because I also found bugs while adding the tests.

**Pull request merged**
