### PR TITLE
Removed become_user=splunk as the become_user

### PR DESCRIPTION
**Pull request by rcabral-splunk**
Also removed become_user from enable_service task as it requires privileges to update /etc/init.d.

### CODE REVIEW

**Comment by dLabsMarijnB** [comment]
Some additional flags should be added to the enable-service in order to make this work.
When not running any before_start_cmd you need to add:
--accept-license --answer-yes --no-prompt

**Comment by rcabral-splunk** [comment]
> Some additional flags should be added to the enable-service in order to make this work.
> When not running any before_start_cmd you need to add:
> --accept-license --answer-yes --no-prompt

Not quite sure I understood your suggestion. Are you proposing to include those flags to enable-boot? If so, those aren't valid parameters for the boot-start.

**Comment by lephino** [comment]
I think as long as this is merged with 
https://github.com/splunk/splunk-ansible/pull/97, you guys hit the needs.

**Comment by dLabsMarijnB** [comment]
I have just tested it again to verify and make sure.

The order in which things get executed in the playbooks means the enable boot-start happens before anything else. (Unless you use the pre-start execution option, which is not a guarantee)
Then:
- You do need the --accept-license at enable boot-start, otherwise it will hang on the license prompt
- You also need the --no-prompt because it will hang at the password input prompt
- And the --answer-yes is just for good measure.

Most of the changes requested I have incorporated into #97.

**Comment by rcabral-splunk** [comment]
Figured out why it's working. `enable_s2s_port` task runs before `enable_service` and it is already passing those parameters. We don't necessarily need to add those to `enable_service` again, because  if it fails, the whole playbook would also do it so. However, it won'r hurt if we also add those extra args as well. Updating the PR with it.

**Comment by nwang92** [comment]
Seems like https://github.com/splunk/splunk-ansible/pull/97 solves this problem + also adds systemd. Maybe we should close this PR in favor of that?

**Comment by rcabral-splunk** [comment]
> Seems like #97 solves this problem + also adds systemd. Maybe we should close this PR in favor of that?

Correct! Sounds good to me.

**Comment by lephino** [comment]
Closing for 97

**Pull request closed without merging**
