### PR TITLE
forward servers fix

### PR DESCRIPTION
**Pull request by tod-uma**
There is a bug where the scripts won't add forward_servers when there isn't a s2s config. I've fixed that bug and added molecule tests to make sure forward_servers continues to work in the future.

### CODE REVIEW

**Comment by tod-uma** [comment]
This pull request still requires EITHER splunk.s2s_port or splunk.s2s.port be specified in the config. Should we set up something in get_facts to set a default for the s2s port since someone may want to have forward_servers, but not any other s2s configuration?

**Comment by nwang92** [comment]
If I understand correctly, there's a bit of misconception in how we're using `splunk.s2s*`. Part of the plays use `splunk.s2s.port` to setup receiving, but the section modified here also uses `splunk.s2s.port` to setup forwarding.

That's been a problem for us recently and we're looking at approaches to resolve it. For instance: https://github.com/splunk/splunk-ansible/issues/383 - although in this case, we need to know the remote instance's management port (assumed to be 9997) whereas in this case, we need to know the remote instance's s2s port (assumed to be 9997). If you have any ideas, feel free to suggest away!

As far as:
> someone may want to have forward_servers, but not any other s2s configuration
That should be the intent of `splunk.s2s.enable` - if this is true, then we will configure this instance for receiving. Otherwise, it should disable receiving. This currently should not impact forwarding, with the exception being that we're using the same port for both.

**Comment by tod-uma** [comment]
> That's been a problem for us recently and we're looking at approaches to resolve it. For instance: #383 - although in this case, we need to know the remote instance's management port (assumed to be 9997) whereas in this case, we need to know the remote instance's s2s port (assumed to be 9997). If you have any ideas, feel free to suggest away!

I could rewrite the forward-servers logic to require you specify the port for each forward server. I'm not sure how I'd do that and keep backwards compatibility without tons of spaghetti logic though.

**Comment by nwang92** [comment]
Yeah, let's leave that as a separate issue. I'm still wrapping my head around how to make it compatible for both environment variable syntax for the docker-splunk work + default.yml for this work.

**Pull request merged**
